import os
import re
import sys
import time
import json
from typing import List, Dict, Any, Optional
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.table import WD_TABLE_ALIGNMENT


class EvidenceCollector:
    def __init__(
        self,
        workspace_dir: str,
        scenario_name: str,
        format_mode: str = "both",
        env: str = "QA",
        browser: str = "msedge"
    ):
        self.workspace_dir = workspace_dir
        self.scenario_name = scenario_name
        self.format_mode = format_mode.lower()
        self.env = env
        self.browser = browser
        self.steps: List[Dict[str, Any]] = []
        self.step_counter = 0
        self._attached_page = None

        self.timestamp_str = time.strftime("%Y%m%d_%H%M%S")
        clean_name = re.sub(r'[^a-zA-Z0-9_-]', '_', scenario_name)
        self.evidence_dir = os.path.join(workspace_dir, "evidence", f"{clean_name}_{self.timestamp_str}")
        self.docx_path = ""

    def attach(self, page):
        self._attached_page = page
        os.makedirs(self.evidence_dir, exist_ok=True)

        orig_goto = page.goto
        def wrapped_goto(url, *args, **kwargs):
            res = orig_goto(url, *args, **kwargs)
            try:
                page.wait_for_load_state("domcontentloaded", timeout=2000)
            except Exception:
                pass
            self.capture_step(f"Navigate to {url}")
            return res
        page.goto = wrapped_goto

        orig_locator = page.locator
        def wrapped_locator(selector, *args, **kwargs):
            loc = orig_locator(selector, *args, **kwargs)

            orig_click = loc.click
            def wrapped_click(*a, **kw):
                res = orig_click(*a, **kw)
                time.sleep(0.2)
                self.capture_step(f"Click element '{selector}'")
                return res
            loc.click = wrapped_click

            orig_fill = loc.fill
            def wrapped_fill(val, *a, **kw):
                res = orig_fill(val, *a, **kw)
                time.sleep(0.1)
                self.capture_step(f"Fill '{selector}' with '{val}'")
                return res
            loc.fill = wrapped_fill

            orig_check = loc.check
            def wrapped_check(*a, **kw):
                res = orig_check(*a, **kw)
                time.sleep(0.1)
                self.capture_step(f"Check checkbox '{selector}'")
                return res
            loc.check = wrapped_check

            orig_select = loc.select_option
            def wrapped_select(*a, **kw):
                res = orig_select(*a, **kw)
                time.sleep(0.1)
                self.capture_step(f"Select option on '{selector}'")
                return res
            loc.select_option = wrapped_select

            return loc
        page.locator = wrapped_locator

    def capture_step(self, description: str, status: str = "Passed"):
        if not self._attached_page:
            return
        self.step_counter += 1
        step_num = str(self.step_counter).zfill(2)
        clean_desc = re.sub(r'[^a-zA-Z0-9_-]', '_', description)[:25]
        img_name = f"step_{step_num}_{clean_desc}.png"
        img_path = os.path.join(self.evidence_dir, img_name)

        try:
            self._attached_page.screenshot(path=img_path)
        except Exception:
            return

        step_data = {
            "step_number": self.step_counter,
            "description": description,
            "image_path": img_path,
            "image_name": img_name,
            "status": status,
            "timestamp": time.strftime("%H:%M:%S")
        }
        self.steps.append(step_data)

    def generate_docx_report(self, test_passed: bool) -> str:
        doc = docx.Document()

        title_p = doc.add_paragraph()
        title_run = title_p.add_run("QA Test Execution Evidence Report")
        title_run.font.size = Pt(20)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(14, 116, 144)

        sub_p = doc.add_paragraph()
        sub_run = sub_p.add_run("Generated by Conduit Standalone Test Automation Desktop Framework")
        sub_run.font.size = Pt(10)
        sub_run.font.italic = True
        sub_run.font.color.rgb = RGBColor(100, 116, 139)

        table = doc.add_table(rows=6, cols=2)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        meta_data = [
            ("Scenario Name", self.scenario_name),
            ("Execution Result", "PASSED" if test_passed else "FAILED"),
            ("Target Environment", self.env),
            ("Browser Engine", self.browser),
            ("Execution Timestamp", time.strftime("%Y-%m-%d %H:%M:%S")),
            ("Total Steps Captured", str(len(self.steps)))
        ]

        for idx, (label, val) in enumerate(meta_data):
            cell_lbl = table.cell(idx, 0)
            cell_val = table.cell(idx, 1)

            p_lbl = cell_lbl.paragraphs[0]
            r_lbl = p_lbl.add_run(label)
            r_lbl.font.bold = True
            r_lbl.font.size = Pt(10)

            p_val = cell_val.paragraphs[0]
            r_val = p_val.add_run(val)
            r_val.font.size = Pt(10)
            if label == "Execution Result":
                r_val.font.bold = True
                if test_passed:
                    r_val.font.color.rgb = RGBColor(16, 185, 129)
                else:
                    r_val.font.color.rgb = RGBColor(239, 68, 68)

        doc.add_paragraph()
        sec_h = doc.add_heading("Chronological Step Evidence", level=1)
        sec_h.paragraph_format.space_before = Pt(16)
        sec_h.paragraph_format.space_after = Pt(8)

        for s in self.steps:
            step_p = doc.add_paragraph()
            step_r = step_p.add_run(f"Step {s['step_number']}: {s['description']}")
            step_r.font.bold = True
            step_r.font.size = Pt(12)
            step_r.font.color.rgb = RGBColor(30, 41, 59)

            meta_p = doc.add_paragraph()
            meta_r = meta_p.add_run(f"Status: {s['status']}   |   Captured At: {s['timestamp']}")
            meta_r.font.size = Pt(9)
            meta_r.font.color.rgb = RGBColor(100, 116, 139)

            img_p = s.get("image_path")
            if img_p and os.path.exists(img_p):
                try:
                    doc.add_picture(img_p, width=Inches(6.0))
                except Exception:
                    pass

            doc.add_paragraph()

        doc_name = f"Evidence_Report_{self.scenario_name}.docx"
        out_path = os.path.join(self.evidence_dir, doc_name)
        doc.save(out_path)
        self.docx_path = out_path
        return out_path

    def finalize(self, test_passed: bool = True) -> Dict[str, Any]:
        summary = {
            "scenario": self.scenario_name,
            "status": "Passed" if test_passed else "Failed",
            "env": self.env,
            "browser": self.browser,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "steps_count": len(self.steps),
            "evidence_dir": self.evidence_dir,
            "steps": self.steps
        }

        sum_path = os.path.join(self.evidence_dir, "summary.json")
        try:
            with open(sum_path, "w", encoding="utf-8") as f:
                json.dump(summary, f, indent=2)
        except Exception:
            pass

        if self.format_mode in ("word", "both"):
            try:
                self.generate_docx_report(test_passed)
            except Exception as e:
                print(f"[Evidence Docx Error]: {e}", file=sys.stderr)

        if self.format_mode == "word":
            for s in self.steps:
                p = s.get("image_path")
                if p and os.path.exists(p):
                    try:
                        os.remove(p)
                    except Exception:
                        pass

        print(f"[CONDUIT_EVIDENCE]: {self.evidence_dir}")
        if self.docx_path:
            print(f"[CONDUIT_DOCX]: {self.docx_path}")

        return summary
